name: Auto-add Issues to Project Board

on:
  issues:
    types: [opened]

permissions:
  issues: read

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue to Project
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/alexander-proudfoot/projects/3
          github-token: ${{ secrets.PROJECT_PAT }}
